language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly
