language: php

sudo: false

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit
