language: php

sudo: false

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix
